#!/bin/bash

BLUE='\e[1;34m'
GREEN='\e[1;32m'
RESET='\e[0m'

echo -e "${BLUE}=== Building project ===${RESET}"
./gradlew jar || exit 1

echo -e "${BLUE}=== Creating Gitingest File ===${RESET}"
uvx gitingest ../utilities-suite/ -e ".github/*" \
    -e ".gradle/*" \
    -e ".vscode/*" \
    -e "bin/*" \
    -e "build/*" \
    -e "gradle/*" \
    || exit 1

echo -e "${BLUE}=== Committing changes ===${RESET}"
git add .
read -p "Commit summary: " summary
read -p "Commit message: " message

if [ -z "$message" ]; then
    git commit -m "$summary"
else
    git commit -m "$summary" -m "$message"
fi

echo -e "${BLUE}=== Pushing ===${RESET}"
git push || exit 1

echo -e "${GREEN}Done!${RESET}"